name: Full-stack CI/CD with Docker Compose

on:
  push:
    branches:
      - main
      - backend
  pull_request:
    branches:
      - main
      - backend
      
jobs:
  docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Compose
        run: |
          cd app 
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build and run Docker Compose services
        run: |
          cd app
          docker-compose -f docker-compose.yml up -d --build  # Build and run containers

    #   - name: Wait for containers to initialize (optional)
    #     run: |
    #       cd app
    #       sleep 30  # Allow time for services to initialize

    #   - name: Run frontend tests (optional)
    #     run: |
    #       cd app
    #       docker-compose exec -T frontend npm test  # Run tests inside the frontend container

    #   - name: Run backend tests (optional)
    #     run: |
    #       cd app/frontend
    #       docker-compose exec -T backend npm test  # Run tests inside the backend container

      - name: Shut down Docker Compose services
        run: |
          cd app
          docker-compose down  # Stops and removes all containers
